volumes:
  n8n_data:
  postgres_data:
  pgvector_data:
  qdrant_data:
  redis_data:
  redisinsight_data:
  minio_data:

networks:
  ai-network:
    driver: bridge

configs:
  qdrant_config:
    content: |
      log_level: INFO

x-n8n: &service-n8n
  image: n8nio/n8n:nightly
  networks: 
    - ai-network
  environment:
      - N8N_HOST=${N8N_HOST:-localhost}
      - N8N_PORT=5678
      - N8N_PROTOCOL=${N8N_PROTOCOL:-http}
      - N8N_EDITOR_BASE_URL=${N8N_WEBHOOK_URL:-${N8N_PROTOCOL:-http}://${N8N_HOST:-localhost}:${N8N_PORT:-5678}}
      - NODE_ENV=development # Set to "production" or "development"
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY:-your-secret-key}
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true # Prevents the settings file from being world-readable
      - N8N_SECURE_COOKIE=false # Disable Prevents the use of cookies over HTTPs
      - N8N_USER_MANAGEMENT_JWT_SECRET=${N8N_USER_MANAGEMENT_JWT_SECRET:-secret-key}
      - N8N_RUNNERS_ENABLED=true # Enable additional runners
      - N8N_RUNNERS_MODE=internal # Set the runners mode to "internal"
      - N8N_PERSONALIZATION=false # Disable personalization
      - WEBHOOK_URL=${N8N_WEBHOOK_URL} # The public URL of the n8n instance
      - DB_TYPE=postgresdb 
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB:-n8n}
      - DB_POSTGRESDB_USER=${POSTGRES_USER:-n8n}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD:-n8n}
      - TZ=${GENERIC_TIMEZONE:-UTC}
      # N8N Logs
      - N8N_LOG_LEVEL=info # Set the log level to "info"
      - N8N_LOG_OUTPUT=console # Set the log output to "console"
      - N8N_LOG_FILE=/home/node/.n8n/logs/n8n.log # Set the log file path
      - N8N_LOG_FILE_MAX_SIZE=120mb # Set the maximum log file size
      - N8N_LOG_FILE_MAX_FILES=10 # Set the maximum number of log files to keep
      - N8N_LOG_FILE_COMPRESSION=true # Enable log file compression
      - N8N_LOG_FILE_ROTATE=true # Enable log file rotation
      - N8N_LOG_FILE_ROTATE_INTERVAL=1d # Set the log file rotation interval
      - OLLAMA_HOST=host.docker.internal:11434

services:
  n8n-import:
    <<: *service-n8n
    hostname: n8n-import
    container_name: n8n-import
    entrypoint: /bin/sh
    command:
      - "-c"
      # Single files Import
      #- "n8n import:credentials --input=/backup/creds.json && n8n import:workflow --input=/backup/flows.json" 
      # Folder Import
      #- "n8n import:credentials --separate --input=/backup/creddentials/ && n8n import:workflow --separate --input=/backup/workflows/" 
    volumes:
      - ./n8n_backup:/backup
    depends_on:
      postgres:
        condition: service_healthy
  n8n:
    <<: *service-n8n
    hostname: n8n
    container_name: n8n
    restart: always
    labels:
      - dev.orbstack.domains=${N8N_HOST:-localhost}
    ports:
      - "5678:5678"
    volumes:
      - ./n8n_data:/home/node/.n8n
      - ./n8n_data/files:/files 
      - ./n8n_backup:/backup
      - ./shared:/data/shared
    depends_on:
      postgres:
        condition: service_healthy
      # n8n-import:
      #   condition: service_completed_successfully
      #   - qdrant


  postgres:
    image: pgvector/pgvector:pg16
    container_name: n8n-postgres
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-n8n}
      - POSTGRES_USER=${POSTGRES_USER:-n8n}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-n8n}
      - POSTGRES_HOST_AUTH_METHOD=trust
      - TZ=${GENERIC_TIMEZONE:-UTC}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    networks:
      - ai-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-admin@racksync.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-admin}
      - TZ=${GENERIC_TIMEZONE:-UTC}
    depends_on:
      - postgres
    ports:
      - "5050:80"
    networks:
      - ai-network
     
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: always
    environment:
      - TZ=${GENERIC_TIMEZONE:-UTC}
      - QDRANT__SERVICE__API_KEY=${QDRANT_API_KEY:-secret-key}
    volumes:
      - ./qdrant_data:/qdrant/storage
    ports:
      - "6333:6333"
      - "6334:6334"
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    networks:
      - ai-network
  
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_ARGS=--requirepass ${REDIS_PASSWORD}
      - TZ=${GENERIC_TIMEZONE:-UTC}
    volumes:
      - redis_data:/data
    networks:
      - ai-network

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    restart: unless-stopped
    ports:
      - "5540:5540"
    environment:
      - TZ=${GENERIC_TIMEZONE:-UTC}
    volumes:
      - redisinsight_data:/data
    networks:
      - ai-network
    depends_on:
      - redis

  minio:
    container_name: minio
    restart: always
    image: quay.io/minio/minio:latest
    ports:
      - "9000:9000" # Please Comment for Internal Access Only
      - "9001:9001"
    networks:
      - ai-network
    volumes:
      - ./minio_data:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-root}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-secret_password}
      - MINIO_SERVER_URL=${MINIO_SERVER_URL:-http://host.docker.internal:9000}  
      - MINIO_ฺBROWSER_REDIRECT_URL=${MINIO_BROWSE_REDIRECT_URL:-http://host.docker.internal:9001}
      - MINIO_REGION_NAME=${MINIO_REGION_NAME:-us-east-1}
      - MINIO_SCHEME=${MINIO_SCHEME:-http}
      - MINIO_DEFAULT_BUCKETS=${MINIO_DEFAULT_BUCKETS:-n8n}
    command: server /data --console-address ":9001"

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${ZEROTRUST_TOKEN}
      - TZ=${GENERIC_TIMEZONE:-UTC}
    networks:
      - ai-network
    # depends_on:
    #   - n8n
      
